# -*- coding: utf-8 -*-
"""Task-3-EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPhDsC-lx_nLWTelCdFCU9g1RBjzLWGI

#Importing Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""#Load the dataset"""

df = sns.load_dataset('iris')

"""#Summary"""

print("First 5 Rows:")
print(df.head())

print("\nDataset Information:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

"""#plot"""

sns.pairplot(df, hue='species')
plt.suptitle("Pairplot of Iris Dataset", y=1.02)
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.select_dtypes(include='number').corr(),annot=True,cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()